apiVersion:                               v1
kind:                                     Template
metadata:
  name:                                   pbw-cicd-pipeline
  annotations:
    openshift.io/display-name: Plants by WebSphere on Liberty CI/CD Pipeline
    description: CI/CD Pipeline for Plants by WebSphere on Liberty App
    tags: liberty,websphere
    openshift.io/provider-display-name: IBM Client Dev Advocacy.
    openshift.io/documentation-url: https://github.com/ibmappmodernization/app-modernization-plants-by-websphere-jee6.git
    openshift.io/support-url: https://access.redhat.com
parameters:
- name:                                   APP_NAME
  description:                            The name assigned to all of the application objects defined in this template.
  displayName:                            Application Name
  required:                               true
  value:                                  pbw-cicd-pipeline
- name:                                   DEPLOYED_APP_NAME
  description:                            The name of the deployed application.
  displayName:                            Deployed Application Name
  required:                               true
  value:                                  pbw-liberty-mariadb
- name:                                   GIT_SOURCE_URL
  description:                            The source URL for the application
  displayName:                            Source URL
  required:                               true
  value:                                  https://github.com/changeme/app-modernization-plants-by-websphere-jee6.git
- name:                                   GIT_SOURCE_REF
  description:                            The source Ref for the application
  displayName:                            Source Ref
  required:                               true
  value:                                  master
- description:                            Github trigger secret.  A difficult to guess string encoded as part of the webhook URL.  Not encrypted.
  displayName:                            GitHub Webhook Secret
  from:                                   '[a-zA-Z0-9]{40}'
  generate:                               expression
  name:                                   GITHUB_WEBHOOK_SECRET
  required:                               true
- description:                            A secret string used to configure the Generic webhook.
  displayName:                            Generic Webhook Secret
  from:                                   '[a-zA-Z0-9]{40}'
  generate:                               expression
  name:                                   GENERIC_WEBHOOK_SECRET
  required:                               true
objects:
  - apiVersion:                           v1
    kind:                                 BuildConfig
    metadata:
      annotations:
        pipeline.alpha.openshift.io/uses: '[{"name": "${NAME}", "namespace": "", "kind": "DeploymentConfig"}]'
      creationTimestamp:                  null
      labels:
        name:                             ${APP_NAME}
      name:                               ${APP_NAME}
    spec:
      source:
        git:
          uri: "${GIT_SOURCE_URL}"
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath:                Jenkinsfile.ocp
          env:
            - name:  "GIT_SOURCE_URL"
              value: "${GIT_SOURCE_URL}"
            - name:  "GIT_SOURCE_REF"
              value: "${GIT_SOURCE_REF}"
            - name: "DEPLOYED_APP_NAME"
              value: "${DEPLOYED_APP_NAME}"
        type:                             JenkinsPipeline
      triggers:
      - github:
          secret:                         "${GITHUB_WEBHOOK_SECRET}"
        type:                             GitHub
      - generic:
          secret:                         "${GENERIC_WEBHOOK_SECRET}"
        type:                             Generic
